"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.protobuf.wrappers_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___IdentifierType = IdentifierType
class _IdentifierType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[IdentifierType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    UnknownIdentifier = IdentifierType.V(0)
    DNSIdentifier = IdentifierType.V(1)
    IPIdentifier = IdentifierType.V(2)
    EmailIdentifier = IdentifierType.V(3)
class IdentifierType(metaclass=_IdentifierType):
    V = typing.NewType('V', builtins.int)
UnknownIdentifier = IdentifierType.V(0)
DNSIdentifier = IdentifierType.V(1)
IPIdentifier = IdentifierType.V(2)
EmailIdentifier = IdentifierType.V(3)

global___ErrorType = ErrorType
class _ErrorType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ErrorType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    ServerInternalError = ErrorType.V(0)
    AccountDoesNotExistError = ErrorType.V(1)
    AlreadyRevokedError = ErrorType.V(2)
    BadCSRError = ErrorType.V(3)
    BadNonceError = ErrorType.V(4)
    BadPublicKeyError = ErrorType.V(5)
    BadRevocationReasonError = ErrorType.V(6)
    BadSignatureAlgorithmError = ErrorType.V(7)
    CAAError = ErrorType.V(8)
    CompoundError = ErrorType.V(9)
    ConnectionError = ErrorType.V(10)
    DNSError = ErrorType.V(11)
    ExternalAccountRequiredError = ErrorType.V(12)
    IncorrectResponseError = ErrorType.V(13)
    InvalidContactError = ErrorType.V(14)
    MalformedError = ErrorType.V(15)
    OrderNotReadyError = ErrorType.V(16)
    RateLimitedError = ErrorType.V(17)
    RejectedIdentifierError = ErrorType.V(18)
    TLSError = ErrorType.V(19)
    UnauthorizedError = ErrorType.V(20)
    UnsupportedContactError = ErrorType.V(21)
    UnsupportedIdentifierError = ErrorType.V(22)
    UserActionRequiredError = ErrorType.V(23)
    AutoRenewalCanceledError = ErrorType.V(24)
    AutoRenewalExpiredError = ErrorType.V(25)
    AutoRenewalCancellationInvalidError = ErrorType.V(26)
    AutoRenewalRevocationNotSupportedError = ErrorType.V(27)
class ErrorType(metaclass=_ErrorType):
    V = typing.NewType('V', builtins.int)
ServerInternalError = ErrorType.V(0)
AccountDoesNotExistError = ErrorType.V(1)
AlreadyRevokedError = ErrorType.V(2)
BadCSRError = ErrorType.V(3)
BadNonceError = ErrorType.V(4)
BadPublicKeyError = ErrorType.V(5)
BadRevocationReasonError = ErrorType.V(6)
BadSignatureAlgorithmError = ErrorType.V(7)
CAAError = ErrorType.V(8)
CompoundError = ErrorType.V(9)
ConnectionError = ErrorType.V(10)
DNSError = ErrorType.V(11)
ExternalAccountRequiredError = ErrorType.V(12)
IncorrectResponseError = ErrorType.V(13)
InvalidContactError = ErrorType.V(14)
MalformedError = ErrorType.V(15)
OrderNotReadyError = ErrorType.V(16)
RateLimitedError = ErrorType.V(17)
RejectedIdentifierError = ErrorType.V(18)
TLSError = ErrorType.V(19)
UnauthorizedError = ErrorType.V(20)
UnsupportedContactError = ErrorType.V(21)
UnsupportedIdentifierError = ErrorType.V(22)
UserActionRequiredError = ErrorType.V(23)
AutoRenewalCanceledError = ErrorType.V(24)
AutoRenewalExpiredError = ErrorType.V(25)
AutoRenewalCancellationInvalidError = ErrorType.V(26)
AutoRenewalRevocationNotSupportedError = ErrorType.V(27)

global___EABSignatureMethod = EABSignatureMethod
class _EABSignatureMethod(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EABSignatureMethod.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    HS256 = EABSignatureMethod.V(0)
    HS384 = EABSignatureMethod.V(1)
    HS512 = EABSignatureMethod.V(2)
    HS1 = EABSignatureMethod.V(3)
class EABSignatureMethod(metaclass=_EABSignatureMethod):
    V = typing.NewType('V', builtins.int)
HS256 = EABSignatureMethod.V(0)
HS384 = EABSignatureMethod.V(1)
HS512 = EABSignatureMethod.V(2)
HS1 = EABSignatureMethod.V(3)

global___OrderStatus = OrderStatus
class _OrderStatus(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[OrderStatus.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    OrderPending = OrderStatus.V(0)
    OrderReady = OrderStatus.V(1)
    OrderProcessing = OrderStatus.V(2)
    OrderValid = OrderStatus.V(3)
    OrderInvalid = OrderStatus.V(4)
class OrderStatus(metaclass=_OrderStatus):
    V = typing.NewType('V', builtins.int)
OrderPending = OrderStatus.V(0)
OrderReady = OrderStatus.V(1)
OrderProcessing = OrderStatus.V(2)
OrderValid = OrderStatus.V(3)
OrderInvalid = OrderStatus.V(4)

global___AuthorizationStatus = AuthorizationStatus
class _AuthorizationStatus(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[AuthorizationStatus.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    AuthorizationPending = AuthorizationStatus.V(0)
    AuthorizationValid = AuthorizationStatus.V(1)
    AuthorizationInvalid = AuthorizationStatus.V(2)
    AuthorizationDeactivated = AuthorizationStatus.V(3)
    AuthorizationExpired = AuthorizationStatus.V(4)
    AuthorizationRevoked = AuthorizationStatus.V(5)
class AuthorizationStatus(metaclass=_AuthorizationStatus):
    V = typing.NewType('V', builtins.int)
AuthorizationPending = AuthorizationStatus.V(0)
AuthorizationValid = AuthorizationStatus.V(1)
AuthorizationInvalid = AuthorizationStatus.V(2)
AuthorizationDeactivated = AuthorizationStatus.V(3)
AuthorizationExpired = AuthorizationStatus.V(4)
AuthorizationRevoked = AuthorizationStatus.V(5)

global___ChallengeType = ChallengeType
class _ChallengeType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ChallengeType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    ChallengeHTTP01 = ChallengeType.V(0)
    ChallengeDNS01 = ChallengeType.V(1)
class ChallengeType(metaclass=_ChallengeType):
    V = typing.NewType('V', builtins.int)
ChallengeHTTP01 = ChallengeType.V(0)
ChallengeDNS01 = ChallengeType.V(1)

global___ChallengeStatus = ChallengeStatus
class _ChallengeStatus(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ChallengeStatus.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    ChallengePending = ChallengeStatus.V(0)
    ChallengeProcessing = ChallengeStatus.V(1)
    ChallengeValid = ChallengeStatus.V(2)
    ChallengeInvalid = ChallengeStatus.V(3)
class ChallengeStatus(metaclass=_ChallengeStatus):
    V = typing.NewType('V', builtins.int)
ChallengePending = ChallengeStatus.V(0)
ChallengeProcessing = ChallengeStatus.V(1)
ChallengeValid = ChallengeStatus.V(2)
ChallengeInvalid = ChallengeStatus.V(3)

global___CertStatus = CertStatus
class _CertStatus(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CertStatus.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    CertUnknown = CertStatus.V(0)
    CertGood = CertStatus.V(1)
    CertRevoked = CertStatus.V(2)
    CertUnissued = CertStatus.V(3)
class CertStatus(metaclass=_CertStatus):
    V = typing.NewType('V', builtins.int)
CertUnknown = CertStatus.V(0)
CertGood = CertStatus.V(1)
CertRevoked = CertStatus.V(2)
CertUnissued = CertStatus.V(3)

global___RevocationReason = RevocationReason
class _RevocationReason(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RevocationReason.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    RevocationUnknown = RevocationReason.V(0)
    RevocationUnspecified = RevocationReason.V(1)
    RevocationKeyCompromise = RevocationReason.V(2)
    RevocationCACompromise = RevocationReason.V(3)
    RevocationAffiliationChanged = RevocationReason.V(4)
    RevocationSuperseded = RevocationReason.V(5)
    RevocationCessationOfOperation = RevocationReason.V(6)
    RevocationCertificateHold = RevocationReason.V(7)
    RevocationRemoveFromCRL = RevocationReason.V(8)
    RevocationPrivilegeWithdrawn = RevocationReason.V(9)
    RevocationAACompromise = RevocationReason.V(10)
class RevocationReason(metaclass=_RevocationReason):
    V = typing.NewType('V', builtins.int)
RevocationUnknown = RevocationReason.V(0)
RevocationUnspecified = RevocationReason.V(1)
RevocationKeyCompromise = RevocationReason.V(2)
RevocationCACompromise = RevocationReason.V(3)
RevocationAffiliationChanged = RevocationReason.V(4)
RevocationSuperseded = RevocationReason.V(5)
RevocationCessationOfOperation = RevocationReason.V(6)
RevocationCertificateHold = RevocationReason.V(7)
RevocationRemoveFromCRL = RevocationReason.V(8)
RevocationPrivilegeWithdrawn = RevocationReason.V(9)
RevocationAACompromise = RevocationReason.V(10)

class Identifier(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_TYPE_FIELD_NUMBER: builtins.int
    IDENTIFIER_FIELD_NUMBER: builtins.int
    id_type: global___IdentifierType.V = ...
    identifier: typing.Text = ...

    def __init__(self,
        *,
        id_type : global___IdentifierType.V = ...,
        identifier : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"id_type",b"id_type",u"identifier",b"identifier"]) -> None: ...
global___Identifier = Identifier

class Error(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ERROR_TYPE_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    DETAIL_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    SUB_PROBLEMS_FIELD_NUMBER: builtins.int
    IDENTIFIER_FIELD_NUMBER: builtins.int
    error_type: global___ErrorType.V = ...
    title: typing.Text = ...
    status: builtins.int = ...
    detail: typing.Text = ...

    @property
    def instance(self) -> google.protobuf.wrappers_pb2.StringValue: ...

    @property
    def sub_problems(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Error]: ...

    @property
    def identifier(self) -> global___Identifier: ...

    def __init__(self,
        *,
        error_type : global___ErrorType.V = ...,
        title : typing.Text = ...,
        status : builtins.int = ...,
        detail : typing.Text = ...,
        instance : typing.Optional[google.protobuf.wrappers_pb2.StringValue] = ...,
        sub_problems : typing.Optional[typing.Iterable[global___Error]] = ...,
        identifier : typing.Optional[global___Identifier] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"identifier",b"identifier",u"instance",b"instance"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"detail",b"detail",u"error_type",b"error_type",u"identifier",b"identifier",u"instance",b"instance",u"status",b"status",u"sub_problems",b"sub_problems",u"title",b"title"]) -> None: ...
global___Error = Error

class ErrorResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ERRORS_FIELD_NUMBER: builtins.int

    @property
    def errors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Error]: ...

    def __init__(self,
        *,
        errors : typing.Optional[typing.Iterable[global___Error]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"errors",b"errors"]) -> None: ...
global___ErrorResponse = ErrorResponse

class ValidateEABRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    KID_FIELD_NUMBER: builtins.int
    SIGNATURE_METHOD_FIELD_NUMBER: builtins.int
    SIGNED_DATA_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    kid: typing.Text = ...
    signature_method: global___EABSignatureMethod.V = ...
    signed_data: builtins.bytes = ...
    signature: builtins.bytes = ...

    def __init__(self,
        *,
        kid : typing.Text = ...,
        signature_method : global___EABSignatureMethod.V = ...,
        signed_data : builtins.bytes = ...,
        signature : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"kid",b"kid",u"signature",b"signature",u"signature_method",b"signature_method",u"signed_data",b"signed_data"]) -> None: ...
global___ValidateEABRequest = ValidateEABRequest

class ValidateEABResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VALID_FIELD_NUMBER: builtins.int
    valid: builtins.bool = ...

    def __init__(self,
        *,
        valid : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"valid",b"valid"]) -> None: ...
global___ValidateEABResponse = ValidateEABResponse

class CreateOrderRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    IDENTIFIERS_FIELD_NUMBER: builtins.int
    NOT_BEFORE_FIELD_NUMBER: builtins.int
    NOT_AFTER_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    EAB_ID_FIELD_NUMBER: builtins.int
    account_id: typing.Text = ...

    @property
    def identifiers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Identifier]: ...

    @property
    def not_before(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def not_after(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def eab_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...

    def __init__(self,
        *,
        identifiers : typing.Optional[typing.Iterable[global___Identifier]] = ...,
        not_before : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        not_after : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        account_id : typing.Text = ...,
        eab_id : typing.Optional[google.protobuf.wrappers_pb2.StringValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"eab_id",b"eab_id",u"not_after",b"not_after",u"not_before",b"not_before"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"account_id",b"account_id",u"eab_id",b"eab_id",u"identifiers",b"identifiers",u"not_after",b"not_after",u"not_before",b"not_before"]) -> None: ...
global___CreateOrderRequest = CreateOrderRequest

class OrderResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ORDER_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int

    @property
    def order(self) -> global___Order: ...

    @property
    def error(self) -> global___ErrorResponse: ...

    def __init__(self,
        *,
        order : typing.Optional[global___Order] = ...,
        error : typing.Optional[global___ErrorResponse] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"error",b"error",u"order",b"order",u"result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"error",b"error",u"order",b"order",u"result",b"result"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"result",b"result"]) -> typing_extensions.Literal["order","error"]: ...
global___OrderResponse = OrderResponse

class AuthorizationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    AUTHORIZATION_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int

    @property
    def authorization(self) -> global___Authorization: ...

    @property
    def error(self) -> global___ErrorResponse: ...

    def __init__(self,
        *,
        authorization : typing.Optional[global___Authorization] = ...,
        error : typing.Optional[global___ErrorResponse] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"authorization",b"authorization",u"error",b"error",u"result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"authorization",b"authorization",u"error",b"error",u"result",b"result"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"result",b"result"]) -> typing_extensions.Literal["authorization","error"]: ...
global___AuthorizationResponse = AuthorizationResponse

class ChallengeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CHALLENGE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int

    @property
    def challenge(self) -> global___Challenge: ...

    @property
    def error(self) -> global___ErrorResponse: ...

    def __init__(self,
        *,
        challenge : typing.Optional[global___Challenge] = ...,
        error : typing.Optional[global___ErrorResponse] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"challenge",b"challenge",u"error",b"error",u"result",b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"challenge",b"challenge",u"error",b"error",u"result",b"result"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"result",b"result"]) -> typing_extensions.Literal["challenge","error"]: ...
global___ChallengeResponse = ChallengeResponse

class IDRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    id: builtins.bytes = ...

    def __init__(self,
        *,
        id : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"id",b"id"]) -> None: ...
global___IDRequest = IDRequest

class FinalizeOrderRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    CSR_FIELD_NUMBER: builtins.int
    id: builtins.bytes = ...
    csr: builtins.bytes = ...

    def __init__(self,
        *,
        id : builtins.bytes = ...,
        csr : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"csr",b"csr",u"id",b"id"]) -> None: ...
global___FinalizeOrderRequest = FinalizeOrderRequest

class Order(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    IDENTIFIERS_FIELD_NUMBER: builtins.int
    NOT_BEFORE_FIELD_NUMBER: builtins.int
    NOT_AFTER_FIELD_NUMBER: builtins.int
    EXPIRES_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    AUTHORIZATIONS_FIELD_NUMBER: builtins.int
    CERTIFICATE_ID_FIELD_NUMBER: builtins.int
    id: builtins.bytes = ...
    status: global___OrderStatus.V = ...
    authorizations: google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes] = ...

    @property
    def identifiers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Identifier]: ...

    @property
    def not_before(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def not_after(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def expires(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def certificate_id(self) -> google.protobuf.wrappers_pb2.BytesValue: ...

    def __init__(self,
        *,
        id : builtins.bytes = ...,
        identifiers : typing.Optional[typing.Iterable[global___Identifier]] = ...,
        not_before : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        not_after : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        expires : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        status : global___OrderStatus.V = ...,
        authorizations : typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        certificate_id : typing.Optional[google.protobuf.wrappers_pb2.BytesValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"certificate_id",b"certificate_id",u"expires",b"expires",u"not_after",b"not_after",u"not_before",b"not_before"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"authorizations",b"authorizations",u"certificate_id",b"certificate_id",u"expires",b"expires",u"id",b"id",u"identifiers",b"identifiers",u"not_after",b"not_after",u"not_before",b"not_before",u"status",b"status"]) -> None: ...
global___Order = Order

class Authorization(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    EXPIRES_FIELD_NUMBER: builtins.int
    IDENTIFIER_FIELD_NUMBER: builtins.int
    CHALLENGES_FIELD_NUMBER: builtins.int
    WILDCARD_FIELD_NUMBER: builtins.int
    id: builtins.bytes = ...
    status: global___AuthorizationStatus.V = ...

    @property
    def expires(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def identifier(self) -> global___Identifier: ...

    @property
    def challenges(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Challenge]: ...

    @property
    def wildcard(self) -> google.protobuf.wrappers_pb2.BoolValue: ...

    def __init__(self,
        *,
        id : builtins.bytes = ...,
        status : global___AuthorizationStatus.V = ...,
        expires : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        identifier : typing.Optional[global___Identifier] = ...,
        challenges : typing.Optional[typing.Iterable[global___Challenge]] = ...,
        wildcard : typing.Optional[google.protobuf.wrappers_pb2.BoolValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"expires",b"expires",u"identifier",b"identifier",u"wildcard",b"wildcard"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"challenges",b"challenges",u"expires",b"expires",u"id",b"id",u"identifier",b"identifier",u"status",b"status",u"wildcard",b"wildcard"]) -> None: ...
global___Authorization = Authorization

class Challenge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    VALIDATED_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    id: builtins.bytes = ...
    type: global___ChallengeType.V = ...
    status: global___ChallengeStatus.V = ...

    @property
    def validated(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def error(self) -> google.protobuf.wrappers_pb2.StringValue: ...

    @property
    def token(self) -> google.protobuf.wrappers_pb2.StringValue: ...

    def __init__(self,
        *,
        id : builtins.bytes = ...,
        type : global___ChallengeType.V = ...,
        status : global___ChallengeStatus.V = ...,
        validated : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        error : typing.Optional[google.protobuf.wrappers_pb2.StringValue] = ...,
        token : typing.Optional[google.protobuf.wrappers_pb2.StringValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"error",b"error",u"token",b"token",u"validated",b"validated"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"error",b"error",u"id",b"id",u"status",b"status",u"token",b"token",u"type",b"type",u"validated",b"validated"]) -> None: ...
global___Challenge = Challenge

class CertificateChain(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CERTIFICATES_FIELD_NUMBER: builtins.int
    certificates: google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes] = ...

    def __init__(self,
        *,
        certificates : typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"certificates",b"certificates"]) -> None: ...
global___CertificateChain = CertificateChain

class CertificateChainResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PRIMARY_CHAIN_FIELD_NUMBER: builtins.int
    ALTERNATIVE_CHAINS_FIELD_NUMBER: builtins.int

    @property
    def primary_chain(self) -> global___CertificateChain: ...

    @property
    def alternative_chains(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CertificateChain]: ...

    def __init__(self,
        *,
        primary_chain : typing.Optional[global___CertificateChain] = ...,
        alternative_chains : typing.Optional[typing.Iterable[global___CertificateChain]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"primary_chain",b"primary_chain"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"alternative_chains",b"alternative_chains",u"primary_chain",b"primary_chain"]) -> None: ...
global___CertificateChainResponse = CertificateChainResponse

class CheckCertRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ISSUER_ID_FIELD_NUMBER: builtins.int
    SERIAL_NUMBER_FIELD_NUMBER: builtins.int
    issuer_id: typing.Text = ...
    serial_number: builtins.bytes = ...

    def __init__(self,
        *,
        issuer_id : typing.Text = ...,
        serial_number : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"issuer_id",b"issuer_id",u"serial_number",b"serial_number"]) -> None: ...
global___CheckCertRequest = CheckCertRequest

class CheckCertResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int
    REVOCATION_REASON_FIELD_NUMBER: builtins.int
    REVOCATION_TIMESTAMP_FIELD_NUMBER: builtins.int
    THIS_UPDATE_FIELD_NUMBER: builtins.int
    NEXT_UPDATE_FIELD_NUMBER: builtins.int
    ARCHIVE_CUTOFF_FIELD_NUMBER: builtins.int
    INVALIDITY_DATE_FIELD_NUMBER: builtins.int
    status: global___CertStatus.V = ...
    revocation_reason: global___RevocationReason.V = ...

    @property
    def revocation_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def this_update(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def next_update(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def archive_cutoff(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def invalidity_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    def __init__(self,
        *,
        status : global___CertStatus.V = ...,
        revocation_reason : global___RevocationReason.V = ...,
        revocation_timestamp : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        this_update : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        next_update : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        archive_cutoff : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        invalidity_date : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"archive_cutoff",b"archive_cutoff",u"invalidity_date",b"invalidity_date",u"next_update",b"next_update",u"revocation_timestamp",b"revocation_timestamp",u"this_update",b"this_update"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"archive_cutoff",b"archive_cutoff",u"invalidity_date",b"invalidity_date",u"next_update",b"next_update",u"revocation_reason",b"revocation_reason",u"revocation_timestamp",b"revocation_timestamp",u"status",b"status",u"this_update",b"this_update"]) -> None: ...
global___CheckCertResponse = CheckCertResponse
