"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _IdentifierType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IdentifierTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IdentifierType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknownIdentifier: _IdentifierType.ValueType  # 0
    DNSIdentifier: _IdentifierType.ValueType  # 1
    IPIdentifier: _IdentifierType.ValueType  # 2
    EmailIdentifier: _IdentifierType.ValueType  # 3

class IdentifierType(_IdentifierType, metaclass=_IdentifierTypeEnumTypeWrapper): ...

UnknownIdentifier: IdentifierType.ValueType  # 0
DNSIdentifier: IdentifierType.ValueType  # 1
IPIdentifier: IdentifierType.ValueType  # 2
EmailIdentifier: IdentifierType.ValueType  # 3
global___IdentifierType = IdentifierType

class _ErrorType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ErrorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ServerInternalError: _ErrorType.ValueType  # 0
    AccountDoesNotExistError: _ErrorType.ValueType  # 1
    AlreadyRevokedError: _ErrorType.ValueType  # 2
    BadCSRError: _ErrorType.ValueType  # 3
    BadNonceError: _ErrorType.ValueType  # 4
    BadPublicKeyError: _ErrorType.ValueType  # 5
    BadRevocationReasonError: _ErrorType.ValueType  # 6
    BadSignatureAlgorithmError: _ErrorType.ValueType  # 7
    CAAError: _ErrorType.ValueType  # 8
    CompoundError: _ErrorType.ValueType  # 9
    ConnectionError: _ErrorType.ValueType  # 10
    DNSError: _ErrorType.ValueType  # 11
    ExternalAccountRequiredError: _ErrorType.ValueType  # 12
    IncorrectResponseError: _ErrorType.ValueType  # 13
    InvalidContactError: _ErrorType.ValueType  # 14
    MalformedError: _ErrorType.ValueType  # 15
    OrderNotReadyError: _ErrorType.ValueType  # 16
    RateLimitedError: _ErrorType.ValueType  # 17
    RejectedIdentifierError: _ErrorType.ValueType  # 18
    TLSError: _ErrorType.ValueType  # 19
    UnauthorizedError: _ErrorType.ValueType  # 20
    UnsupportedContactError: _ErrorType.ValueType  # 21
    UnsupportedIdentifierError: _ErrorType.ValueType  # 22
    UserActionRequiredError: _ErrorType.ValueType  # 23
    AutoRenewalCanceledError: _ErrorType.ValueType  # 24
    AutoRenewalExpiredError: _ErrorType.ValueType  # 25
    AutoRenewalCancellationInvalidError: _ErrorType.ValueType  # 26
    AutoRenewalRevocationNotSupportedError: _ErrorType.ValueType  # 27

class ErrorType(_ErrorType, metaclass=_ErrorTypeEnumTypeWrapper): ...

ServerInternalError: ErrorType.ValueType  # 0
AccountDoesNotExistError: ErrorType.ValueType  # 1
AlreadyRevokedError: ErrorType.ValueType  # 2
BadCSRError: ErrorType.ValueType  # 3
BadNonceError: ErrorType.ValueType  # 4
BadPublicKeyError: ErrorType.ValueType  # 5
BadRevocationReasonError: ErrorType.ValueType  # 6
BadSignatureAlgorithmError: ErrorType.ValueType  # 7
CAAError: ErrorType.ValueType  # 8
CompoundError: ErrorType.ValueType  # 9
ConnectionError: ErrorType.ValueType  # 10
DNSError: ErrorType.ValueType  # 11
ExternalAccountRequiredError: ErrorType.ValueType  # 12
IncorrectResponseError: ErrorType.ValueType  # 13
InvalidContactError: ErrorType.ValueType  # 14
MalformedError: ErrorType.ValueType  # 15
OrderNotReadyError: ErrorType.ValueType  # 16
RateLimitedError: ErrorType.ValueType  # 17
RejectedIdentifierError: ErrorType.ValueType  # 18
TLSError: ErrorType.ValueType  # 19
UnauthorizedError: ErrorType.ValueType  # 20
UnsupportedContactError: ErrorType.ValueType  # 21
UnsupportedIdentifierError: ErrorType.ValueType  # 22
UserActionRequiredError: ErrorType.ValueType  # 23
AutoRenewalCanceledError: ErrorType.ValueType  # 24
AutoRenewalExpiredError: ErrorType.ValueType  # 25
AutoRenewalCancellationInvalidError: ErrorType.ValueType  # 26
AutoRenewalRevocationNotSupportedError: ErrorType.ValueType  # 27
global___ErrorType = ErrorType

class _ValidationMethod:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ValidationMethodEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ValidationMethod.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Http01: _ValidationMethod.ValueType  # 0
    Dns01: _ValidationMethod.ValueType  # 1
    TlsAlpn01: _ValidationMethod.ValueType  # 2
    OnionCSR01: _ValidationMethod.ValueType  # 3

class ValidationMethod(_ValidationMethod, metaclass=_ValidationMethodEnumTypeWrapper): ...

Http01: ValidationMethod.ValueType  # 0
Dns01: ValidationMethod.ValueType  # 1
TlsAlpn01: ValidationMethod.ValueType  # 2
OnionCSR01: ValidationMethod.ValueType  # 3
global___ValidationMethod = ValidationMethod

class _EABSignatureMethod:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EABSignatureMethodEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EABSignatureMethod.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    HS256: _EABSignatureMethod.ValueType  # 0
    HS384: _EABSignatureMethod.ValueType  # 1
    HS512: _EABSignatureMethod.ValueType  # 2
    HS1: _EABSignatureMethod.ValueType  # 3

class EABSignatureMethod(_EABSignatureMethod, metaclass=_EABSignatureMethodEnumTypeWrapper): ...

HS256: EABSignatureMethod.ValueType  # 0
HS384: EABSignatureMethod.ValueType  # 1
HS512: EABSignatureMethod.ValueType  # 2
HS1: EABSignatureMethod.ValueType  # 3
global___EABSignatureMethod = EABSignatureMethod

class _OrderStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OrderStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OrderStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OrderPending: _OrderStatus.ValueType  # 0
    OrderReady: _OrderStatus.ValueType  # 1
    OrderProcessing: _OrderStatus.ValueType  # 2
    OrderValid: _OrderStatus.ValueType  # 3
    OrderInvalid: _OrderStatus.ValueType  # 4

class OrderStatus(_OrderStatus, metaclass=_OrderStatusEnumTypeWrapper): ...

OrderPending: OrderStatus.ValueType  # 0
OrderReady: OrderStatus.ValueType  # 1
OrderProcessing: OrderStatus.ValueType  # 2
OrderValid: OrderStatus.ValueType  # 3
OrderInvalid: OrderStatus.ValueType  # 4
global___OrderStatus = OrderStatus

class _AuthorizationStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AuthorizationStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AuthorizationStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    AuthorizationPending: _AuthorizationStatus.ValueType  # 0
    AuthorizationValid: _AuthorizationStatus.ValueType  # 1
    AuthorizationInvalid: _AuthorizationStatus.ValueType  # 2
    AuthorizationDeactivated: _AuthorizationStatus.ValueType  # 3
    AuthorizationExpired: _AuthorizationStatus.ValueType  # 4
    AuthorizationRevoked: _AuthorizationStatus.ValueType  # 5

class AuthorizationStatus(_AuthorizationStatus, metaclass=_AuthorizationStatusEnumTypeWrapper): ...

AuthorizationPending: AuthorizationStatus.ValueType  # 0
AuthorizationValid: AuthorizationStatus.ValueType  # 1
AuthorizationInvalid: AuthorizationStatus.ValueType  # 2
AuthorizationDeactivated: AuthorizationStatus.ValueType  # 3
AuthorizationExpired: AuthorizationStatus.ValueType  # 4
AuthorizationRevoked: AuthorizationStatus.ValueType  # 5
global___AuthorizationStatus = AuthorizationStatus

class _ChallengeType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ChallengeTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ChallengeType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ChallengeHTTP01: _ChallengeType.ValueType  # 0
    ChallengeDNS01: _ChallengeType.ValueType  # 1
    ChallengeTLSALPN01: _ChallengeType.ValueType  # 2
    ChallengeOnionCSR01: _ChallengeType.ValueType  # 3

class ChallengeType(_ChallengeType, metaclass=_ChallengeTypeEnumTypeWrapper): ...

ChallengeHTTP01: ChallengeType.ValueType  # 0
ChallengeDNS01: ChallengeType.ValueType  # 1
ChallengeTLSALPN01: ChallengeType.ValueType  # 2
ChallengeOnionCSR01: ChallengeType.ValueType  # 3
global___ChallengeType = ChallengeType

class _ChallengeStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ChallengeStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ChallengeStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ChallengePending: _ChallengeStatus.ValueType  # 0
    ChallengeProcessing: _ChallengeStatus.ValueType  # 1
    ChallengeValid: _ChallengeStatus.ValueType  # 2
    ChallengeInvalid: _ChallengeStatus.ValueType  # 3

class ChallengeStatus(_ChallengeStatus, metaclass=_ChallengeStatusEnumTypeWrapper): ...

ChallengePending: ChallengeStatus.ValueType  # 0
ChallengeProcessing: ChallengeStatus.ValueType  # 1
ChallengeValid: ChallengeStatus.ValueType  # 2
ChallengeInvalid: ChallengeStatus.ValueType  # 3
global___ChallengeStatus = ChallengeStatus

class _CertStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CertStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CertStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CertUnknown: _CertStatus.ValueType  # 0
    CertGood: _CertStatus.ValueType  # 1
    CertRevoked: _CertStatus.ValueType  # 2
    CertUnissued: _CertStatus.ValueType  # 3

class CertStatus(_CertStatus, metaclass=_CertStatusEnumTypeWrapper): ...

CertUnknown: CertStatus.ValueType  # 0
CertGood: CertStatus.ValueType  # 1
CertRevoked: CertStatus.ValueType  # 2
CertUnissued: CertStatus.ValueType  # 3
global___CertStatus = CertStatus

class _RevocationReason:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RevocationReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RevocationReason.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RevocationUnknown: _RevocationReason.ValueType  # 0
    RevocationUnspecified: _RevocationReason.ValueType  # 1
    RevocationKeyCompromise: _RevocationReason.ValueType  # 2
    RevocationCACompromise: _RevocationReason.ValueType  # 3
    RevocationAffiliationChanged: _RevocationReason.ValueType  # 4
    RevocationSuperseded: _RevocationReason.ValueType  # 5
    RevocationCessationOfOperation: _RevocationReason.ValueType  # 6
    RevocationCertificateHold: _RevocationReason.ValueType  # 7
    RevocationRemoveFromCRL: _RevocationReason.ValueType  # 8
    RevocationPrivilegeWithdrawn: _RevocationReason.ValueType  # 9
    RevocationAACompromise: _RevocationReason.ValueType  # 10

class RevocationReason(_RevocationReason, metaclass=_RevocationReasonEnumTypeWrapper): ...

RevocationUnknown: RevocationReason.ValueType  # 0
RevocationUnspecified: RevocationReason.ValueType  # 1
RevocationKeyCompromise: RevocationReason.ValueType  # 2
RevocationCACompromise: RevocationReason.ValueType  # 3
RevocationAffiliationChanged: RevocationReason.ValueType  # 4
RevocationSuperseded: RevocationReason.ValueType  # 5
RevocationCessationOfOperation: RevocationReason.ValueType  # 6
RevocationCertificateHold: RevocationReason.ValueType  # 7
RevocationRemoveFromCRL: RevocationReason.ValueType  # 8
RevocationPrivilegeWithdrawn: RevocationReason.ValueType  # 9
RevocationAACompromise: RevocationReason.ValueType  # 10
global___RevocationReason = RevocationReason

@typing_extensions.final
class Identifier(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_TYPE_FIELD_NUMBER: builtins.int
    IDENTIFIER_FIELD_NUMBER: builtins.int
    id_type: global___IdentifierType.ValueType
    identifier: builtins.str
    def __init__(
        self,
        *,
        id_type: global___IdentifierType.ValueType = ...,
        identifier: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id_type", b"id_type", "identifier", b"identifier"]) -> None: ...

global___Identifier = Identifier

@typing_extensions.final
class Error(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_TYPE_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    DETAIL_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    SUB_PROBLEMS_FIELD_NUMBER: builtins.int
    IDENTIFIER_FIELD_NUMBER: builtins.int
    error_type: global___ErrorType.ValueType
    title: builtins.str
    status: builtins.int
    detail: builtins.str
    @property
    def instance(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def sub_problems(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Error]: ...
    @property
    def identifier(self) -> global___Identifier: ...
    def __init__(
        self,
        *,
        error_type: global___ErrorType.ValueType = ...,
        title: builtins.str = ...,
        status: builtins.int = ...,
        detail: builtins.str = ...,
        instance: google.protobuf.wrappers_pb2.StringValue | None = ...,
        sub_problems: collections.abc.Iterable[global___Error] | None = ...,
        identifier: global___Identifier | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["identifier", b"identifier", "instance", b"instance"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["detail", b"detail", "error_type", b"error_type", "identifier", b"identifier", "instance", b"instance", "status", b"status", "sub_problems", b"sub_problems", "title", b"title"]) -> None: ...

global___Error = Error

@typing_extensions.final
class ErrorResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERRORS_FIELD_NUMBER: builtins.int
    @property
    def errors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Error]: ...
    def __init__(
        self,
        *,
        errors: collections.abc.Iterable[global___Error] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["errors", b"errors"]) -> None: ...

global___ErrorResponse = ErrorResponse

@typing_extensions.final
class KeyValidationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    ACCOUNT_THUMBPRINT_FIELD_NUMBER: builtins.int
    IDENTIFIER_FIELD_NUMBER: builtins.int
    HS_PRIVATE_KEY_FIELD_NUMBER: builtins.int
    token: builtins.str
    account_thumbprint: builtins.str
    @property
    def identifier(self) -> global___Identifier: ...
    hs_private_key: builtins.bytes
    def __init__(
        self,
        *,
        token: builtins.str = ...,
        account_thumbprint: builtins.str = ...,
        identifier: global___Identifier | None = ...,
        hs_private_key: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["identifier", b"identifier"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_thumbprint", b"account_thumbprint", "hs_private_key", b"hs_private_key", "identifier", b"identifier", "token", b"token"]) -> None: ...

global___KeyValidationRequest = KeyValidationRequest

@typing_extensions.final
class OnionCSRValidationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CSR_FIELD_NUMBER: builtins.int
    CA_NONCE_FIELD_NUMBER: builtins.int
    IDENTIFIER_FIELD_NUMBER: builtins.int
    csr: builtins.bytes
    ca_nonce: builtins.bytes
    @property
    def identifier(self) -> global___Identifier: ...
    def __init__(
        self,
        *,
        csr: builtins.bytes = ...,
        ca_nonce: builtins.bytes = ...,
        identifier: global___Identifier | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["identifier", b"identifier"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ca_nonce", b"ca_nonce", "csr", b"csr", "identifier", b"identifier"]) -> None: ...

global___OnionCSRValidationRequest = OnionCSRValidationRequest

@typing_extensions.final
class CAACheckRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALIDATION_METHOD_FIELD_NUMBER: builtins.int
    IDENTIFIER_FIELD_NUMBER: builtins.int
    ACCOUNT_URI_FIELD_NUMBER: builtins.int
    HS_PRIVATE_KEY_FIELD_NUMBER: builtins.int
    ONION_CAA_FIELD_NUMBER: builtins.int
    validation_method: global___ValidationMethod.ValueType
    @property
    def identifier(self) -> global___Identifier: ...
    @property
    def account_uri(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    hs_private_key: builtins.bytes
    @property
    def onion_caa(self) -> global___OnionCAA: ...
    def __init__(
        self,
        *,
        validation_method: global___ValidationMethod.ValueType = ...,
        identifier: global___Identifier | None = ...,
        account_uri: google.protobuf.wrappers_pb2.StringValue | None = ...,
        hs_private_key: builtins.bytes = ...,
        onion_caa: global___OnionCAA | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_uri", b"account_uri", "identifier", b"identifier", "onion_caa", b"onion_caa"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_uri", b"account_uri", "hs_private_key", b"hs_private_key", "identifier", b"identifier", "onion_caa", b"onion_caa", "validation_method", b"validation_method"]) -> None: ...

global___CAACheckRequest = CAACheckRequest

@typing_extensions.final
class OnionCAA(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CAA_FIELD_NUMBER: builtins.int
    EXPIRY_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    caa: builtins.str
    expiry: builtins.int
    signature: builtins.bytes
    def __init__(
        self,
        *,
        caa: builtins.str = ...,
        expiry: builtins.int = ...,
        signature: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["caa", b"caa", "expiry", b"expiry", "signature", b"signature"]) -> None: ...

global___OnionCAA = OnionCAA

@typing_extensions.final
class ValidationResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALID_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    valid: builtins.bool
    @property
    def error(self) -> global___ErrorResponse: ...
    def __init__(
        self,
        *,
        valid: builtins.bool = ...,
        error: global___ErrorResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["error", b"error", "valid", b"valid"]) -> None: ...

global___ValidationResult = ValidationResult

@typing_extensions.final
class ValidateEABRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KID_FIELD_NUMBER: builtins.int
    SIGNATURE_METHOD_FIELD_NUMBER: builtins.int
    SIGNED_DATA_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    kid: builtins.str
    signature_method: global___EABSignatureMethod.ValueType
    signed_data: builtins.bytes
    signature: builtins.bytes
    def __init__(
        self,
        *,
        kid: builtins.str = ...,
        signature_method: global___EABSignatureMethod.ValueType = ...,
        signed_data: builtins.bytes = ...,
        signature: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["kid", b"kid", "signature", b"signature", "signature_method", b"signature_method", "signed_data", b"signed_data"]) -> None: ...

global___ValidateEABRequest = ValidateEABRequest

@typing_extensions.final
class ValidateEABResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALID_FIELD_NUMBER: builtins.int
    valid: builtins.bool
    def __init__(
        self,
        *,
        valid: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["valid", b"valid"]) -> None: ...

global___ValidateEABResponse = ValidateEABResponse

@typing_extensions.final
class CreateOrderRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIERS_FIELD_NUMBER: builtins.int
    NOT_BEFORE_FIELD_NUMBER: builtins.int
    NOT_AFTER_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    EAB_ID_FIELD_NUMBER: builtins.int
    @property
    def identifiers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Identifier]: ...
    @property
    def not_before(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def not_after(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    account_id: builtins.str
    @property
    def eab_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        identifiers: collections.abc.Iterable[global___Identifier] | None = ...,
        not_before: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        not_after: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        account_id: builtins.str = ...,
        eab_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["eab_id", b"eab_id", "not_after", b"not_after", "not_before", b"not_before"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "eab_id", b"eab_id", "identifiers", b"identifiers", "not_after", b"not_after", "not_before", b"not_before"]) -> None: ...

global___CreateOrderRequest = CreateOrderRequest

@typing_extensions.final
class CreateAuthorizationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    EAB_ID_FIELD_NUMBER: builtins.int
    @property
    def identifier(self) -> global___Identifier: ...
    account_id: builtins.str
    @property
    def eab_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        identifier: global___Identifier | None = ...,
        account_id: builtins.str = ...,
        eab_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["eab_id", b"eab_id", "identifier", b"identifier"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "eab_id", b"eab_id", "identifier", b"identifier"]) -> None: ...

global___CreateAuthorizationRequest = CreateAuthorizationRequest

@typing_extensions.final
class OrderResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def order(self) -> global___Order: ...
    @property
    def error(self) -> global___ErrorResponse: ...
    def __init__(
        self,
        *,
        order: global___Order | None = ...,
        error: global___ErrorResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error", b"error", "order", b"order", "result", b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["error", b"error", "order", b"order", "result", b"result"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["result", b"result"]) -> typing_extensions.Literal["order", "error"] | None: ...

global___OrderResponse = OrderResponse

@typing_extensions.final
class AuthorizationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHORIZATION_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def authorization(self) -> global___Authorization: ...
    @property
    def error(self) -> global___ErrorResponse: ...
    def __init__(
        self,
        *,
        authorization: global___Authorization | None = ...,
        error: global___ErrorResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["authorization", b"authorization", "error", b"error", "result", b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["authorization", b"authorization", "error", b"error", "result", b"result"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["result", b"result"]) -> typing_extensions.Literal["authorization", "error"] | None: ...

global___AuthorizationResponse = AuthorizationResponse

@typing_extensions.final
class ChallengeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHALLENGE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def challenge(self) -> global___Challenge: ...
    @property
    def error(self) -> global___ErrorResponse: ...
    def __init__(
        self,
        *,
        challenge: global___Challenge | None = ...,
        error: global___ErrorResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["challenge", b"challenge", "error", b"error", "result", b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["challenge", b"challenge", "error", b"error", "result", b"result"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["result", b"result"]) -> typing_extensions.Literal["challenge", "error"] | None: ...

global___ChallengeResponse = ChallengeResponse

@typing_extensions.final
class IDRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.bytes
    def __init__(
        self,
        *,
        id: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___IDRequest = IDRequest

@typing_extensions.final
class ChallengeIDRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    AUTH_ID_FIELD_NUMBER: builtins.int
    id: builtins.bytes
    auth_id: builtins.bytes
    def __init__(
        self,
        *,
        id: builtins.bytes = ...,
        auth_id: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["auth_id", b"auth_id", "id", b"id"]) -> None: ...

global___ChallengeIDRequest = ChallengeIDRequest

@typing_extensions.final
class CompleteChallengeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    AUTH_ID_FIELD_NUMBER: builtins.int
    ACCOUNT_THUMBPRINT_FIELD_NUMBER: builtins.int
    ACCOUNT_URI_FIELD_NUMBER: builtins.int
    CSR_FIELD_NUMBER: builtins.int
    id: builtins.bytes
    auth_id: builtins.bytes
    account_thumbprint: builtins.str
    account_uri: builtins.str
    csr: builtins.bytes
    def __init__(
        self,
        *,
        id: builtins.bytes = ...,
        auth_id: builtins.bytes = ...,
        account_thumbprint: builtins.str = ...,
        account_uri: builtins.str = ...,
        csr: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["csr", b"csr", "response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_thumbprint", b"account_thumbprint", "account_uri", b"account_uri", "auth_id", b"auth_id", "csr", b"csr", "id", b"id", "response", b"response"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["response", b"response"]) -> typing_extensions.Literal["csr"] | None: ...

global___CompleteChallengeRequest = CompleteChallengeRequest

@typing_extensions.final
class FinalizeOrderRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CSR_FIELD_NUMBER: builtins.int
    id: builtins.bytes
    csr: builtins.bytes
    def __init__(
        self,
        *,
        id: builtins.bytes = ...,
        csr: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["csr", b"csr", "id", b"id"]) -> None: ...

global___FinalizeOrderRequest = FinalizeOrderRequest

@typing_extensions.final
class Order(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    IDENTIFIERS_FIELD_NUMBER: builtins.int
    NOT_BEFORE_FIELD_NUMBER: builtins.int
    NOT_AFTER_FIELD_NUMBER: builtins.int
    EXPIRES_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    AUTHORIZATIONS_FIELD_NUMBER: builtins.int
    CERTIFICATE_ID_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    id: builtins.bytes
    @property
    def identifiers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Identifier]: ...
    @property
    def not_before(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def not_after(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def expires(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    status: global___OrderStatus.ValueType
    @property
    def authorizations(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def certificate_id(self) -> google.protobuf.wrappers_pb2.BytesValue: ...
    @property
    def error(self) -> global___ErrorResponse: ...
    def __init__(
        self,
        *,
        id: builtins.bytes = ...,
        identifiers: collections.abc.Iterable[global___Identifier] | None = ...,
        not_before: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        not_after: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        expires: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        status: global___OrderStatus.ValueType = ...,
        authorizations: collections.abc.Iterable[builtins.bytes] | None = ...,
        certificate_id: google.protobuf.wrappers_pb2.BytesValue | None = ...,
        error: global___ErrorResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["certificate_id", b"certificate_id", "error", b"error", "expires", b"expires", "not_after", b"not_after", "not_before", b"not_before"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["authorizations", b"authorizations", "certificate_id", b"certificate_id", "error", b"error", "expires", b"expires", "id", b"id", "identifiers", b"identifiers", "not_after", b"not_after", "not_before", b"not_before", "status", b"status"]) -> None: ...

global___Order = Order

@typing_extensions.final
class Authorization(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    EXPIRES_FIELD_NUMBER: builtins.int
    IDENTIFIER_FIELD_NUMBER: builtins.int
    CHALLENGES_FIELD_NUMBER: builtins.int
    WILDCARD_FIELD_NUMBER: builtins.int
    id: builtins.bytes
    status: global___AuthorizationStatus.ValueType
    @property
    def expires(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def identifier(self) -> global___Identifier: ...
    @property
    def challenges(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Challenge]: ...
    @property
    def wildcard(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        id: builtins.bytes = ...,
        status: global___AuthorizationStatus.ValueType = ...,
        expires: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        identifier: global___Identifier | None = ...,
        challenges: collections.abc.Iterable[global___Challenge] | None = ...,
        wildcard: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["expires", b"expires", "identifier", b"identifier", "wildcard", b"wildcard"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["challenges", b"challenges", "expires", b"expires", "id", b"id", "identifier", b"identifier", "status", b"status", "wildcard", b"wildcard"]) -> None: ...

global___Authorization = Authorization

@typing_extensions.final
class RevokeCertRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    AUTHZ_CHECKED_FIELD_NUMBER: builtins.int
    ISSUER_ID_FIELD_NUMBER: builtins.int
    SERIAL_NUMBER_FIELD_NUMBER: builtins.int
    REVOCATION_REASON_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    authz_checked: builtins.bool
    issuer_id: builtins.str
    serial_number: builtins.bytes
    @property
    def revocation_reason(self) -> google.protobuf.wrappers_pb2.UInt32Value: ...
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
        authz_checked: builtins.bool = ...,
        issuer_id: builtins.str = ...,
        serial_number: builtins.bytes = ...,
        revocation_reason: google.protobuf.wrappers_pb2.UInt32Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["revocation_reason", b"revocation_reason"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "authz_checked", b"authz_checked", "issuer_id", b"issuer_id", "revocation_reason", b"revocation_reason", "serial_number", b"serial_number"]) -> None: ...

global___RevokeCertRequest = RevokeCertRequest

@typing_extensions.final
class RevokeCertResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> global___ErrorResponse: ...
    def __init__(
        self,
        *,
        error: global___ErrorResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["error", b"error"]) -> None: ...

global___RevokeCertResponse = RevokeCertResponse

@typing_extensions.final
class Challenge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    VALIDATED_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    AUTH_KEY_FIELD_NUMBER: builtins.int
    NONCE_FIELD_NUMBER: builtins.int
    id: builtins.bytes
    type: global___ChallengeType.ValueType
    status: global___ChallengeStatus.ValueType
    @property
    def validated(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def error(self) -> global___ErrorResponse: ...
    @property
    def token(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    auth_key: builtins.bytes
    nonce: builtins.bytes
    def __init__(
        self,
        *,
        id: builtins.bytes = ...,
        type: global___ChallengeType.ValueType = ...,
        status: global___ChallengeStatus.ValueType = ...,
        validated: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        error: global___ErrorResponse | None = ...,
        token: google.protobuf.wrappers_pb2.StringValue | None = ...,
        auth_key: builtins.bytes = ...,
        nonce: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error", b"error", "token", b"token", "validated", b"validated"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["auth_key", b"auth_key", "error", b"error", "id", b"id", "nonce", b"nonce", "status", b"status", "token", b"token", "type", b"type", "validated", b"validated"]) -> None: ...

global___Challenge = Challenge

@typing_extensions.final
class CertificateChain(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CERTIFICATES_FIELD_NUMBER: builtins.int
    @property
    def certificates(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        certificates: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["certificates", b"certificates"]) -> None: ...

global___CertificateChain = CertificateChain

@typing_extensions.final
class CertificateChainResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRIMARY_CHAIN_FIELD_NUMBER: builtins.int
    ALTERNATIVE_CHAINS_FIELD_NUMBER: builtins.int
    @property
    def primary_chain(self) -> global___CertificateChain: ...
    @property
    def alternative_chains(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CertificateChain]: ...
    def __init__(
        self,
        *,
        primary_chain: global___CertificateChain | None = ...,
        alternative_chains: collections.abc.Iterable[global___CertificateChain] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["primary_chain", b"primary_chain"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["alternative_chains", b"alternative_chains", "primary_chain", b"primary_chain"]) -> None: ...

global___CertificateChainResponse = CertificateChainResponse

@typing_extensions.final
class CheckCertRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISSUER_ID_FIELD_NUMBER: builtins.int
    SERIAL_NUMBER_FIELD_NUMBER: builtins.int
    issuer_id: builtins.str
    serial_number: builtins.bytes
    def __init__(
        self,
        *,
        issuer_id: builtins.str = ...,
        serial_number: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["issuer_id", b"issuer_id", "serial_number", b"serial_number"]) -> None: ...

global___CheckCertRequest = CheckCertRequest

@typing_extensions.final
class CheckCertResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    REVOCATION_REASON_FIELD_NUMBER: builtins.int
    REVOCATION_TIMESTAMP_FIELD_NUMBER: builtins.int
    THIS_UPDATE_FIELD_NUMBER: builtins.int
    NEXT_UPDATE_FIELD_NUMBER: builtins.int
    ARCHIVE_CUTOFF_FIELD_NUMBER: builtins.int
    INVALIDITY_DATE_FIELD_NUMBER: builtins.int
    status: global___CertStatus.ValueType
    revocation_reason: global___RevocationReason.ValueType
    @property
    def revocation_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def this_update(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def next_update(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def archive_cutoff(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def invalidity_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        status: global___CertStatus.ValueType = ...,
        revocation_reason: global___RevocationReason.ValueType = ...,
        revocation_timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        this_update: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        next_update: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        archive_cutoff: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        invalidity_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["archive_cutoff", b"archive_cutoff", "invalidity_date", b"invalidity_date", "next_update", b"next_update", "revocation_timestamp", b"revocation_timestamp", "this_update", b"this_update"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["archive_cutoff", b"archive_cutoff", "invalidity_date", b"invalidity_date", "next_update", b"next_update", "revocation_reason", b"revocation_reason", "revocation_timestamp", b"revocation_timestamp", "status", b"status", "this_update", b"this_update"]) -> None: ...

global___CheckCertResponse = CheckCertResponse
