[default]
address = "::1"
tos_uri = "https://as207960.net/assets/docs/AS207960_T_C_s.pdf"
tos_agreed_to_after = "2023-03-18T00:00:00Z"
website_uri = "https://as207960.net"
caa_identities = ["bjorn.as207960.net"]
ca_grpc_uri = "http://[::1]:50051"
external_uris = ["https://acme-onions.eu.ngrok.io", "https://acme-onions-2.eu.ngrok.io"]
tor_storage = "./tor-storage"

[[default.acme_issuers]]
cert_id = "a"
issuer_cert_file = "python-ca/ca-certs/intermediate-crt.pem"

[[default.ocsp_issuers]]
cert_id = "a"
issuer_cert_file = "python-ca/ca-certs/intermediate-crt.pem"
signer_pkcs12_file = "ocsp-signer.p12"
grpc_uri = "http://[::1]:50051"

[global.databases]
db = { url = "postgres://postgres@localhost/bjorn" }
