# Generated by Django 3.2.6 on 2021-08-30 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AccountKey',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('secret', models.BinaryField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bjorn.account')),
            ],
        ),
    ]
