# Generated by Django 3.2.6 on 2021-08-30 16:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bjorn', '0003_auto_20210830_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acme_account_id', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('p', 'Pending'), ('v', 'Valid'), ('i', 'Invalid')], max_length=1)),
                ('expires_at', models.DateTimeField()),
                ('deactivated', models.BooleanField(blank=True)),
                ('revoked', models.BooleanField(blank=True)),
                ('id_type', models.CharField(choices=[('dns', 'DNS')], max_length=64)),
                ('identifier', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acme_account_id', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('csr', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accountkey',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='bjorn.account'),
        ),
        migrations.AlterField(
            model_name='accountkey',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OrderIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[('dns', 'DNS')], max_length=64)),
                ('identifier', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='bjorn.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bjorn.authorization')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='bjorn.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bjorn.account'),
        ),
        migrations.AddField(
            model_name='authorization',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='bjorn.account'),
        ),
    ]
