# Generated by Django 3.2.6 on 2021-09-02 13:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bjorn', '0004_auto_20210830_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuingCert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cert', models.BinaryField()),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='bjorn.issuingcert')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ee_cert', models.BinaryField()),
                ('issued_at', models.DateTimeField()),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ee_certificates', to='bjorn.issuingcert')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='certificate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bjorn.certificate'),
        ),
    ]
