# Generated by Django 3.2.6 on 2021-09-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjorn', '0005_auto_20210902_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuingcert',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
