# Generated by Django 3.2.6 on 2021-09-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjorn', '0008_auto_20210902_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='invalidity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revocation_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unspecified'), (2, 'Key compromise'), (3, 'CA compromise'), (4, 'Affiliation changed'), (5, 'Superseded'), (6, 'Cessation of operation'), (7, 'Certificate hold'), (8, 'Remove from CRL'), (9, 'Privilege withdrawn'), (10, 'AA compromise')], default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revocation_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
