# Generated by Django 3.2.6 on 2021-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjorn', '0009_auto_20210908_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='revocation_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unspecified'), (2, 'Key compromise'), (3, 'CA compromise'), (4, 'Affiliation changed'), (5, 'Superseded'), (6, 'Cessation of operation'), (7, 'Certificate hold'), (8, 'Remove from CRL'), (9, 'Privilege withdrawn'), (10, 'AA compromise')], null=True),
        ),
    ]
