# Generated by Django 3.2.6 on 2021-09-08 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bjorn', '0010_alter_certificate_revocation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('processing', models.BooleanField(blank=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(choices=[('h', 'HTTP-01')], max_length=1)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='bjorn.authorization')),
            ],
        ),
    ]
