# Generated by Django 3.2.6 on 2021-10-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjorn', '0012_alter_authorizationchallenge_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationchallenge',
            name='processing',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='authorizationchallenge',
            name='type',
            field=models.CharField(choices=[('h', 'http-01'), ('d', 'dns-01'), ('t', 'tls-alpn-01')], max_length=1),
        ),
    ]
